using System;
using System.Reflection;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("4.1.0.3001")]
[assembly: AssemblyInformationalVersionAttribute("4.1.0.CR1")]
[assembly: AssemblyFileVersionAttribute("4.1.0.3001")]

